version: '3.4'

services:
  management.db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    
  management.api:
    image: elpatrondaniel/autimelogger.api:latest
    build:
      context: .
      dockerfile: src/Management.Api/Dockerfile
    depends_on:
      - management.db